@AspireRagDemo.API_HostAddress = http://localhost:56288

GET  http://localhost:56288/embedding?input=hello
Accept: application/json

###
# @timeout 60000
GET  http://localhost:5026/rag?input="What is the purpose of this repository? Also what is the name?"
Accept: application/json
