@AspireRagDemo.API_HostAddress = http://localhost:56288

GET  http://localhost:5026/embedding?query=hello
Accept: application/json

###
# @timeout 60000
GET  http://localhost:5026/vector-search?query="What is the purpose of .Net Aspire? Also what is the name?"
Accept: application/json

###
# @timeout 60000
GET  http://localhost:5026/chat-with-context?query="What is the purpose of .Net Aspire? And why does it matter?"
Accept: application/json


###
# @timeout 60000
GET  http://localhost:5026/chat?query="What is the purpose of this repository? Also what is the name?"
Accept: application/json

 